export const LF_LISTMY_REQUEST = "LF_LISTMY_REQUEST";
export const LF_LISTMY_SUCCESS  = "LF_LISTMY_SUCCESS ";
export const LF_LISTMY_FAIL = "LF_LIST_FAIL";
export const LF_LISTMY_RESET= "LF_LISTMY_RESET";