export const CAT_LIST_REQUEST = "CAT_LIST_REQUEST";
export const CAT_LIST_SUCCESS = "CAT_LIST_SUCCESS";
export const CAT_LIST_FAIL = "CAT_LIST_FAIL";
export const CAT_LIST_RESET = "CAT_LIST_RESET";

export const DOG_LIST_REQUEST = "DOG_LIST_REQUEST";
export const DOG_LIST_SUCCESS = "DOG_LIST_SUCCESS";
export const DOG_LIST_FAIL = "DOG_LIST_FAIL";
export const DOG_LIST_RESET = "DOG_LIST_RESET";

export const PETS_LIST_REQUEST = "PETS_LIST_REQUEST";
export const PETS_LIST_SUCCESS = "PETS_LIST_SUCCESS";
export const PETS_LIST_FAIL = "PETS_LIST_FAIL";
export const PETS_LIST_RESET = "PETS_LIST_RESET";

export const PET_DETAILS_REQUEST = "PET_DETAILS_REQUEST";
export const PET_DETAILS_SUCCESS = "PET_DETAILS_SUCCESS";
export const PET_DETAILS_FAIL = "PET_DETAILS_FAIL";
export const PET_DETAILS_RESET = "PET_DETAILS_RESET";

export const PET_UPDATE_REQUEST = "PET_UPDATE_REQUEST";
export const PET_UPDATE_SUCCESS = "PET_UPDATE_SUCCESS";
export const PET_UPDATE_FAIL = "PET_UPDATE_FAIL";
export const PET_UPDATE_RESET = "PET_UPDATE_RESET";

export const PET_DELETE_REQUEST = "PET_DELETE_REQUEST";
export const PET_DELETE_SUCCESS = "PET_DELETE_SUCCESS";
export const PET_DELETE_FAIL = "PET_DELETE_FAIL";

export const CAT_LISTMY_REQUEST = "CAT_LISTMY_REQUEST";
export const CAT_LISTMY_SUCCESS = "CAT_LISTMY_SUCCESS";
export const CAT_LISTMY_FAIL = "CAT_LISTMY_FAIL";
export const CAT_LISTMY_RESET = "CAT_LISTMY_RESET";

export const DOG_LISTMY_REQUEST = "DOG_LISTMY_REQUEST";
export const DOG_LISTMY_SUCCESS = "DOG_LISTMY_SUCCESS";
export const DOG_LISTMY_FAIL = "DOG_LISTMY_FAIL";
export const DOG_LISTMY_RESET = "DOG_LISTMY_RESET";

export const DOG_DETAILS_REQUEST = "DOG_DETAILS_REQUEST";
export const DOG_DETAILS_SUCCESS = "DOG_DETAILS_SUCCESS";
export const DOG_DETAILS_FAIL = "DOG_DETAILS_FAIL";
export const DOG_DETAILS_RESET = "DOG_DETAILS_RESET";

export const DOG_UPDATE_REQUEST = "DOG_UPDATE_REQUEST";
export const DOG_UPDATE_SUCCESS = "DOG_UPDATE_SUCCESS";
export const DOG_UPDATE_FAIL = "DOG_UPDATE_FAIL";
export const DOG_UPDATE_RESET = "DOG_UPDATE_RESET";

export const DOG_DELETE_REQUEST = "DOG_DELETE_REQUEST";
export const DOG_DELETE_SUCCESS = "DOG_DELETE_SUCCESS";
export const DOG_DELETE_FAIL = "DOG_DELETE_FAIL";
