# Generated by Django 4.2 on 2023-04-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_delete_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
