# Generated by Django 4.1.7 on 2023-05-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_forgotpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindPet',
            fields=[
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default=False, max_length=200)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('pTag', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
