# Generated by Django 4.2 on 2023-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_verifyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
