# Generated by Django 4.2 on 2023-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_finddog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finddog',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
