# Generated by Django 4.2 on 2023-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_alter_finddog_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finddog',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='findpet',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
