# Generated by Django 4.2 on 2023-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_catimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimage',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
